### ISSUE TITLE
一个关于布局的建议

### ISSUE THREAD

**Issue by unix** [HelipengTony/odoc#1]
Hi，@HelipengTony，这个项目看起来很酷！👍 

我在[这里](https://github.com/HelipengTony/odoc/blob/f7a18c9a878b5a79d8454e935d0f23f34a2085c7/src/pages/_app.tsx#L109)注意到类似于 `. aside` 等元素需要在一定的宽度下隐藏，以获得更好的响应式体验。这里可以试试 `Grid` 组件的自动隐藏设计：

```jsx
<Grid.Container>
  <Grid xs={24} sm={18}>content</Grid>
  <Grid xs={0} sm={6}>aside</Grid>
</Grid.Container>
```

如果 `Grid` 或是 `Grid.Container` 在一个断点被设置了 `0`，那么它会自动隐藏，这是基于 CSS 媒体查询的，也可以与服务端渲染兼容。如果你有一天需要进行任何的改动，比如在一定宽度下更换位置或是浮动等更复杂的响应式体验，也可以试试 `useMediaQuery` 钩子。

**Comment by HelipengTony** [comment]
@unix 感谢你的建议！
听起来是个非常有趣的想法，我稍晚会在此项目中进行尝试。
另外，我其实是将此项目视为 React 入门的实践，这意味着我会随着技能水平的提高和丰富逐步完善它。
BTW，你的 UI Kit 非常棒！
