### ISSUE TITLE
支持 dalao，关于侧边栏排序

### ISSUE THREAD

**Issue by vcheckzen** [HelipengTony/odoc#2]
还没测试，之前用 vuepress 时，如果通过扫描文件（夹）生成侧边栏，基本没法指定顺序，或者可维护性不强。首先，按名称排序满足不了需求。其次，如果手动为文件（夹）添加序号，按序号排，以后在中间插入新文件（夹）时，其后序号都要依次更改。第三，按创建时间排序有相同问题。最后是在文件夹内添加 next 文件，指向下个文件夹；文件头写入 next 变量，指向下一篇文章。从用户角度，这似乎是平衡新建和插入文件（夹）易用性较好的办法，不知 dalao 怎么看。

**Comment by HelipengTony** [comment]
感谢你的建议和经验分享。
之前的想法 (目前未在开发) 是在每一个文件夹内手动添加一个书写入侧边栏项目排序列表及对应文件名的 JSON 文件。你的想法听起来可行，有时间的话麻烦详细描述一下实现 / 提供一个 Demo / 提交一个 PR 吧。此外，近期本项目维护缓慢，所以非常欢迎你直接进行贡献!
